### ISSUE TITLE
Request Database sql 

### ISSUE THREAD

**Issue by fahri-atmaja** [ramdannur/RentCar#1]
boleh minta database sqlnya gan? email: fahrizalaziz54@gmail.com

**Comment by ramdannur** [comment]
Database sql nya sudah saya hapus, tapi seharusnya masih bisa di akses..
Coba saja buka link yg ini : [db_ujikom.sql ](https://github.com/ramdannur/RentCar/commit/0b90c3e09fdce48e42e68df46d688ea15c771735#diff-c2ff9ce54a0d601c477d8dd3156d11b8)
